# https://github.com/codecov/example-python

version: 2.1
orbs:
  python: circleci/python@1.5.0
  codecov: codecov/codecov@3.0.0

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.9.6
    steps:
      - checkout
      - run
          name: Install and run tests
          command: |
            pip install -r requirements.txt
            coverage run tests/test_superpose3d.py
            coverage xml
      - codecov/upload

workflow:
  version: 2.1
  build-test:
    jobs:
      - build-and-test