version: 2.1
orbs:
  codecov: codecov/codecov@3.0.0

jobs:
  build:
    docker:
      - image: cimg/python:3.9.6
    steps:
      - checkout
      - run:
          name: Install
          command: pip install -r requirements.txt
      - run:
          name: Run Tests
          command: |
            coverage run tests/test_superpose3d.py
            coverage xml
      - codecov/upload

workflow:
  version: 2.1
  build-test:
    jobs:
      - build

# This file was adapted from:
# https://github.com/codecov/example-python/blob/master/.circleci/config.yml
